services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/app
        working_dir: /app
    nginx:
        image: nginx:1.21.4-alpine
        volumes:
            - ./:/app
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - 80:80
        working_dir: /app
